// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_LOGO1.h"
#include "ui_LOGO2.h"
#include "ui_LOGIN.h"
#include "ui_HoldToUnlock.h"
#include "ui_Unlock.h"
#include "ui_Recording.h"
#include "ui_HoldToUpload.h"
#include "ui_Uploading.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_0_intro_png);   // assets/0_intro.png
LV_IMG_DECLARE( ui_img_1_logo_png);   // assets/1_logo.png
LV_IMG_DECLARE( ui_img_4_login_png);   // assets/4_login.png
LV_IMG_DECLARE( ui_img_3a_unlock_png);   // assets/3a_unlock.png
LV_IMG_DECLARE( ui_img_3b_unlock_png);   // assets/3b_unlock.png
LV_IMG_DECLARE( ui_img_5_recording_png);   // assets/5_recording.png
LV_IMG_DECLARE( ui_img_1051634396);   // assets/6_upload-2.png
LV_IMG_DECLARE( ui_img_6_upload_png);   // assets/6_upload.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
