// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_HoldToUnlock;
lv_obj_t *ui_HoldToUnlock = NULL;lv_obj_t *ui_Image7 = NULL;
// event funtions

// build funtions

void ui_HoldToUnlock_screen_init(void)
{
ui_HoldToUnlock = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HoldToUnlock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image7 = lv_img_create(ui_HoldToUnlock);
lv_img_set_src(ui_Image7, &ui_img_3a_unlock_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_HoldToUnlock = ui_HoldToUnlock;

}

void ui_HoldToUnlock_screen_destroy(void)
{
   if (ui_HoldToUnlock) lv_obj_del(ui_HoldToUnlock);

// NULL screen variables
uic_HoldToUnlock= NULL;
ui_HoldToUnlock= NULL;
ui_Image7= NULL;

}
