// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOLDTOUPLOAD_H
#define UI_HOLDTOUPLOAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HoldToUpload
extern void ui_HoldToUpload_screen_init(void);
extern void ui_HoldToUpload_screen_destroy(void);
extern lv_obj_t *ui_HoldToUpload;
extern lv_obj_t *ui_Image11;
// CUSTOM VARIABLES
extern lv_obj_t *uic_HoldToUpload;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

