// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_HoldToUpload;
lv_obj_t *ui_HoldToUpload = NULL;lv_obj_t *ui_Image11 = NULL;
// event funtions

// build funtions

void ui_HoldToUpload_screen_init(void)
{
ui_HoldToUpload = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HoldToUpload, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image11 = lv_img_create(ui_HoldToUpload);
lv_img_set_src(ui_Image11, &ui_img_1051634396);
lv_obj_set_width( ui_Image11, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image11, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_HoldToUpload = ui_HoldToUpload;

}

void ui_HoldToUpload_screen_destroy(void)
{
   if (ui_HoldToUpload) lv_obj_del(ui_HoldToUpload);

// NULL screen variables
uic_HoldToUpload= NULL;
ui_HoldToUpload= NULL;
ui_Image11= NULL;

}
