// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOLDTOUNLOCK_H
#define UI_HOLDTOUNLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HoldToUnlock
extern void ui_HoldToUnlock_screen_init(void);
extern void ui_HoldToUnlock_screen_destroy(void);
extern lv_obj_t *ui_HoldToUnlock;
extern lv_obj_t *ui_Image7;
// CUSTOM VARIABLES
extern lv_obj_t *uic_HoldToUnlock;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

