// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LOGO1_H
#define UI_LOGO1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LOGO1
extern void ui_LOGO1_screen_init(void);
extern void ui_LOGO1_screen_destroy(void);
extern lv_obj_t *ui_LOGO1;
extern lv_obj_t *ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_LOGO1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

