// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LOGIN_H
#define UI_LOGIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LOGIN
extern void ui_LOGIN_screen_init(void);
extern void ui_LOGIN_screen_destroy(void);
extern lv_obj_t *ui_LOGIN;
extern lv_obj_t *ui_Image6;
// CUSTOM VARIABLES
extern lv_obj_t *uic_LOGIN;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

