// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_LOGIN;
lv_obj_t *ui_LOGIN = NULL;lv_obj_t *ui_Image6 = NULL;
// event funtions

// build funtions

void ui_LOGIN_screen_init(void)
{
ui_LOGIN = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LOGIN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image6 = lv_img_create(ui_LOGIN);
lv_img_set_src(ui_Image6, &ui_img_4_login_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_LOGIN = ui_LOGIN;

}

void ui_LOGIN_screen_destroy(void)
{
   if (ui_LOGIN) lv_obj_del(ui_LOGIN);

// NULL screen variables
uic_LOGIN= NULL;
ui_LOGIN= NULL;
ui_Image6= NULL;

}
