// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_LOGO1;
lv_obj_t *ui_LOGO1 = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions

// build funtions

void ui_LOGO1_screen_init(void)
{
ui_LOGO1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LOGO1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_LOGO1);
lv_img_set_src(ui_Image2, &ui_img_0_intro_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_LOGO1 = ui_LOGO1;

}

void ui_LOGO1_screen_destroy(void)
{
   if (ui_LOGO1) lv_obj_del(ui_LOGO1);

// NULL screen variables
uic_LOGO1= NULL;
ui_LOGO1= NULL;
ui_Image2= NULL;

}
