// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LOGO2_H
#define UI_LOGO2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LOGO2
extern void ui_LOGO2_screen_init(void);
extern void ui_LOGO2_screen_destroy(void);
extern lv_obj_t *ui_LOGO2;
extern lv_obj_t *ui_Image3;
// CUSTOM VARIABLES
extern lv_obj_t *uic_LOGO2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

