// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Recording;
lv_obj_t *ui_Recording = NULL;lv_obj_t *ui_Image9 = NULL;
// event funtions

// build funtions

void ui_Recording_screen_init(void)
{
ui_Recording = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Recording, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_Recording);
lv_img_set_src(ui_Image9, &ui_img_5_recording_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Recording = ui_Recording;

}

void ui_Recording_screen_destroy(void)
{
   if (ui_Recording) lv_obj_del(ui_Recording);

// NULL screen variables
uic_Recording= NULL;
ui_Recording= NULL;
ui_Image9= NULL;

}
