// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Uploading;
lv_obj_t *ui_Uploading = NULL;lv_obj_t *ui_Image10 = NULL;
// event funtions

// build funtions

void ui_Uploading_screen_init(void)
{
ui_Uploading = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Uploading, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image10 = lv_img_create(ui_Uploading);
lv_img_set_src(ui_Image10, &ui_img_6_upload_png);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Uploading = ui_Uploading;

}

void ui_Uploading_screen_destroy(void)
{
   if (ui_Uploading) lv_obj_del(ui_Uploading);

// NULL screen variables
uic_Uploading= NULL;
ui_Uploading= NULL;
ui_Image10= NULL;

}
