// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Unlock;
lv_obj_t *ui_Unlock = NULL;lv_obj_t *ui_Image8 = NULL;
// event funtions

// build funtions

void ui_Unlock_screen_init(void)
{
ui_Unlock = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Unlock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_img_create(ui_Unlock);
lv_img_set_src(ui_Image8, &ui_img_3b_unlock_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_Unlock = ui_Unlock;

}

void ui_Unlock_screen_destroy(void)
{
   if (ui_Unlock) lv_obj_del(ui_Unlock);

// NULL screen variables
uic_Unlock= NULL;
ui_Unlock= NULL;
ui_Image8= NULL;

}
