// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_UPLOADING_H
#define UI_UPLOADING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Uploading
extern void ui_Uploading_screen_init(void);
extern void ui_Uploading_screen_destroy(void);
extern lv_obj_t *ui_Uploading;
extern lv_obj_t *ui_Image10;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Uploading;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

