// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_UNLOCK_H
#define UI_UNLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Unlock
extern void ui_Unlock_screen_init(void);
extern void ui_Unlock_screen_destroy(void);
extern lv_obj_t *ui_Unlock;
extern lv_obj_t *ui_Image8;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Unlock;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

